from __future__ import annotations

import io
from uuid import uuid4

import pytest
from PIL import Image

from app.ingestion.factory import create_ingestion_pipeline
from app.ingestion.schemas import (
    ContentBlockType,
    IngestionRequest,
    InputType,
)


def create_test_image() -> bytes:
    """Create a small valid PNG image in memory."""

    image = Image.new(
        "RGB",
        (120, 80),
        "white",
    )

    buffer = io.BytesIO()

    image.save(
        buffer,
        format="PNG",
    )

    return buffer.getvalue()


@pytest.mark.asyncio
async def test_image_flows_through_production_ingestion_pipeline():
    """
    Verify that an image can travel through the real
    production ingestion pipeline:

        detector
            ↓
        processor router
            ↓
        image processor
            ↓
        content normalizer
            ↓
        canonical content
    """

    pipeline = create_ingestion_pipeline()

    image_bytes = create_test_image()

    request = IngestionRequest(
        project_id=uuid4(),
        input_type=InputType.IMAGE,
        title="Test Image",
        filename="test.png",
        mime_type="image/png",
        content=image_bytes,
    )

    result = await pipeline.run(request)

    assert result is not None

    assert result.source.source_type == InputType.IMAGE

    assert result.title == "Test Image"

    assert result.segments

    assert len(result.segments) == 1

    block = result.segments[0]

    assert block.block_type == ContentBlockType.IMAGE

    assert block.order == 0

    assert block.content == ""

    assert result.metadata["ocr"]["status"] == "not_processed"
    assert result.metadata["vision"]["status"] == "not_processed"


@pytest.mark.asyncio
async def test_image_pipeline_preserves_image_metadata():
    """
    Verify that image metadata generated by the image
    processor survives canonical normalization.
    """

    pipeline = create_ingestion_pipeline()

    image_bytes = create_test_image()

    request = IngestionRequest(
        project_id=uuid4(),
        input_type=InputType.IMAGE,
        title="Metadata Test",
        filename="metadata.png",
        mime_type="image/png",
        content=image_bytes,
    )

    result = await pipeline.run(request)

    block = result.segments[0]

    assert block.block_type == ContentBlockType.IMAGE

    assert block.metadata["format"] == "PNG"

    assert block.metadata["width"] == 120

    assert block.metadata["height"] == 80

    assert block.metadata["mode"] == "RGB"


@pytest.mark.asyncio
async def test_image_pipeline_preserves_content_hash():
    """
    Verify that the deterministic SHA-256 image hash is
    preserved through the complete ingestion pipeline.
    """

    pipeline = create_ingestion_pipeline()

    image_bytes = create_test_image()

    request = IngestionRequest(
        project_id=uuid4(),
        input_type=InputType.IMAGE,
        title="Hash Test",
        filename="hash.png",
        mime_type="image/png",
        content=image_bytes,
    )

    result = await pipeline.run(request)

    assert result.source.content_hash

    assert len(result.source.content_hash) == 64

    assert all(
        character in "0123456789abcdef"
        for character in result.source.content_hash
    )


def test_production_router_supports_image():
    """
    Verify that the production processor registry contains
    an image processor.
    """

    pipeline = create_ingestion_pipeline()

    assert pipeline.router.supports(
        InputType.IMAGE
    )


def test_production_router_returns_image_processor():
    """
    Verify that IMAGE resolves to ImageDocumentProcessor.
    """

    pipeline = create_ingestion_pipeline()

    processor = pipeline.router.get_processor(
        InputType.IMAGE
    )

    assert processor.__class__.__name__ == (
        "ImageDocumentProcessor"
    )